<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.klsjnh</groupId>
        <artifactId>java17-lowcode011</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>java17-lowcode011-infrastructure</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.klsjnh</groupId>
            <artifactId>java17-lowcode011-domain</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.klsjnh</groupId>
            <artifactId>java17-infrastructure011</artifactId>
            <version>${framework.version}</version>
        </dependency>
        <dependency>
            <groupId>com.klsjnh</groupId>
            <artifactId>java17-common011</artifactId>
            <version>${framework.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
